# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da49a982da4224602f46f51d06e961002b8e0a5df61d4bbe58bd88d1cb14af1a9815202036d31b17c3d4f4127a31757904051d9c2162371bed4dd106a0023d6a

test:
  secret_key_base: f0ffa33b324f0f43667bd8578799e2842e9326eea41315c3534b2c5d651936553cc69506fad9f9fdbda5335538a556f6e57eb1386e01ab8dd0b792cc4c52aa29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
